import type { Metadata, Viewport } from 'next'
import Script from 'next/script'

import 'tailwindcss/tailwind.css'

import '@/styles/global.css'
import Providers from '@/components/navigation/Providers'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
    viewportFit: 'cover',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <head />
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
